channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.0.2
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.0
  - numpy==2.2.0
  - pandas==2.2.3
  - pygame==2.6.1
  - torch==2.5.1
  - tqdm==4.67.1
name: mlflow-env
